name: Run Auto Many Packets

on:
  workflow_dispatch:
  
jobs:
  dump-packets:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        mcVersionIndex: ["1.8", "1.9", "1.10"]

    steps:
    
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
        
    - name: Setup Java JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        java-package: jre

    - name: Use Dumper
      run: |
        npm i -g prismarine-packet-dumper
        generateMinecraftPackets ${{ matrix.mcVersionIndex }}
        rm -Rf server/ && rm -Rf versions/
        mkdir ${{ matrix.mcVersionIndex }}
        mv packets/* ./${{ matrix.mcVersionIndex }}/
        rm -Rf packets
        rm -Rf launcher_accounts.json
        ls
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: packets
        path: .

  compile-and-commit:
    needs: dump-packets
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
      with:
        persist-credentials: false
        fetch-depth: 0
        
    - name: make artifacts dir
      run: mkdir data/pc/artifacts
        
    - name: my-artifact
      uses: actions/download-artifact@v2
      with:
        name: packets
        path: data/pc/artifacts
        
    - name: Delete all folders we want to overwrite
      run: |
        cd data/pc/artifacts
        for d in */.; do ! test -d ../"$d" || rm -Rf ../"$d"; done
        cd .. && mv artifacts/* .
        rm -Rf artifacts
        
    - name: ls
      run: ls -R
